activeRecord/config/routes.rb
Rails.application.routes.draw do

  root :to => 'sessions#new'
  
  resources :users

  resources :records do
    resources :comments
  end

  resources :tracks
  resources :sessions
  

end

activeRecord/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :record
  # attr_accessible :body, :record_id, :user_id
end

activeRecord/app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  # attr_accessible :album_title, :artist, :genre, :owner_opinion, :release_year, :user_id

  validates :album_title, presence: true
  validates :artist, presence: true
  validates :genre, presence: true
  validates :release_year, presence: true
  validates :owner_opinion, presence: true
  
end

activeRecord/app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :record
  # attr_accessible :title, :record_id
end

activeRecord/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :records
  has_many :comments
  # attr_accessible :password, :username
end

activeRecord/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authorize
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/' unless current_user
  end


end

activeRecord/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authorize

  def new
    @comment = Comment.new
    @record = Record.find_by_id(params[:record_id])
  end

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to @comment.record
    else
      render 'new'
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:body,
                                     :record_id,
                                     :user_id)
    end

end

activeRecord/app/controllers/records_controller.rb
class RecordsController < ApplicationController

  skip_before_action :authorize

  def index
    @records = Record.all
  end

  def show
    @record = Record.find(params[:id])
    @comments = @record.comments
  end

  def new
    @record = Record.new
  end

  def edit
    @record = Record.find(params[:id])
  end

  def update
    @record = Record.find(params[:id])

    if @record.update(record_params)
       redirect_to @record
     else
       render 'edit'
     end
  end


  def create
    @record = Record.new(record_params)

    if @record.save
      redirect_to @record
    else
      render 'new'
    end
  end


  def delete


  end


private

  def record_params
    params.require(:record).permit(:album_title, 
                                   :artist, 
                                   :genre, 
                                   :release_year,
                                   :owner_opinion,
                                   :user_id)
  end




end

activeRecord/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :authorize

  def new
    cur_user = User.new
  end

  def create
    cur_user = User.find_by_username(params[:session][:username])
    if cur_user && cur_user.authenticate(params[:session][:password])
      session[:user_id] = cur_user.id
      redirect_to '/users'
    else
      redirect_to '/'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end


end

activeRecord/app/controllers/tracks_controller.rb
class TrackController < ApplicationController

  # before_filter :authorize
end

activeRecord/app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :authorize
  
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)

    if user.save
      session[:user_id] = user.id
      redirect_to '/records'
    else
      redirect_to '/'
    end
  end

private
  def user_params
    params.require(:user).permit(:username, :password)
  end


end

activeRecord/app/helpers/application_helper.rb
module ApplicationHelper
end

activeRecord/app/views/comments/new.html.erb
<%= form_for :comment, url: record_comments_path do |f| %>
  
<% if @comment.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@comment.errors.count, "error") %>
      prohibited this comment from being saved:
    </h2>

    <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>

  </div>
<% end %>

<%= f.hidden_field :user_id, :value => current_user.id %>
<%= f.hidden_field :record_id, :value => @record.id %>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

activeRecord/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">


<head>
  <title>Activerecord</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>


<body>
  <header>
    <span id='title'>activeRecords</span>
      <nav>
         <ul>
          <% if current_user %>
              <li>Welcome, <%= current_user.username %></li> | 
              <li><%= link_to 'my records', users_path %></li> | 
              <li><%= link_to 'browse collections', records_path %></li> | 
              <li><%= link_to 'logout', session_path(session),
              method: :delete %></li>
            <% else %>
              <li><%= link_to 'Login', new_session_path %></li> | 
              <li><%= link_to 'Register', new_user_path %></li>
          <% end %>
        </ul>
      </nav>
  </header>

  <div id='container'>
    <%= yield %>
  </div>

</body>
</html>

activeRecord/app/views/records/_record_comments.html.erb
<% if current_user %>
  <%= button_to 'Add a comment', new_record_comment_path(@record, @comment), :class => "button", :method => :get  %>

 <% end %> 


<% @comments.each do |comment| %>
<p>
  <%= comment.user.username %> says...<br>
  <%= comment.body %>
  <br>
  <% if current_user.id == comment.user.id %>
     <button>
       <a href="#">Edit comment</a>
     </button>

     <button>
       <a href="#">Delete comment</a>
     </button>

  <% end %>
  <br>
</p> 
<% end %>

activeRecord/app/views/records/edit.html.erb
<%= form_for :record, url: record_path(@record), method: :put do |f| %>

<% if @record.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@record.errors.count, "error") %>
      prohibited this article from being saved:
    </h2>

    <ul>
      <% @record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>

  </div>
<% end %>


  <p>
    <%= f.label :album_title %><br>
    <%= f.text_field :album_title %>
  </p>
 
  <p>
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </p>
 
  <p>
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </p>

  <p>
    <%= f.label :release_year %><br>
    <%= f.text_field :release_year %>
  </p>

  <p>
    <%= f.label :owner_opinion %><br>
    <%= f.text_area :owner_opinion %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

activeRecord/app/views/records/index.html.erb
<table>
<% @records.each do |record| %>


<tr>
  <td> <%= link_to record.album_title, record_path(record) %></td>
  <td> <%= record.artist %> </td>
</tr>

<% end %>

</table>

activeRecord/app/views/records/new.html.erb
<%= form_for :record, url: records_path  do |f| %>
  
<% if @record.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@record.errors.count, "error") %>
      prohibited this record from being saved:
    </h2>

    <ul>
      <% @record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>

  </div>
<% end %>

<%= f.hidden_field :user_id, :value => current_user.id %>

  <p>
    <%= f.label :album_title %><br>
    <%= f.text_field :album_title %>
  </p>
 
  <p>
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </p>
 
  <p>
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </p>

  <p>
    <%= f.label :release_year %><br>
    <%= f.text_field :release_year %>
  </p>

  <p>
    <%= f.label :owner_opinion %><br>
    <%= f.text_area :owner_opinion %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

activeRecord/app/views/records/show.html.erb
<p>
    <strong>Album Title:</strong>
    <%= @record.album_title %>
</p>

<div class='record-info'>
  <h2>Album Info</h2>
  <p>Album Title: <%= @record.album_title %></p> 
  <p>Album Artist: <%= @record.artist %></p> 
  <p>Album Genre: <%= @record.genre %></p> 
  <p>Released: <%= @record.release_year %></p>
  <p><i><%= @record.user.username %>'s opinion:<br></i> <%= @record.owner_opinion %></p>

</div>

<% if current_user.id == @record.user.id %>
   <%= button_to 'Edit this record', edit_record_path(@record), :class => "button", :method => :get  %>
<% end %>

<hr>

<div class='records/record-comments'>
  <h2>Comments</h2>

<%= render "record_comments" %>
</div>

activeRecord/app/views/users/index.html.erb
<div class="my-collections">
  <h2>My Collection</h2>
    <% current_user.records.each do |record| %>
      <p>
        <%= link_to record.album_title, record_path(record) %> by <i><%= record.artist %></i>
      </p>
    <% end %>

   <%= button_to 'add record', new_record_path,:class => "button", :method => :get  %>

</div>

activeRecord/app/views/users/new.html.erb
<%= form_for @user do |f| %>

<p>
  Register for activeRecords
</p>

<p>
  <%= f.label :username %><br>
  <%= f.text_field :username %>
</p>

<p>
  <%= f.label :password %><br>
  <%= f.password_field :password %>
</p>

<p>
  <%= f.label :password %><br>
  <%= f.password_field :password_confirmation %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>